[build]
  base    = ""
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"

[context.production.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200